apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-job-migrations"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["sh", "-c", "alembic upgrade head"]
        env:
        - name: DB_DRIVER_SYNC
          valueFrom:
            configMapKeyRef:
              name: {{ include "users-app.configMapName" . | quote }}
              key: DB_DRIVER_SYNC 
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "users-app.configMapName" . | quote }}
              key: DB_PORT           
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "users-app.configMapName" . | quote }}
              key: DB_HOST   
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.auth.existingSecret }} 
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.auth.existingSecret }} 
              key: password 
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.auth.existingSecret }} 
              key: database 
      restartPolicy: Never  # Не перезапускать контейнер, если он завершился (даже с ошибкой)
  backoffLimit: 4  # Максимальное количество попыток, если Job завершается с ошибкой