apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "users-app.serviceMonitorName" . }}-nginx
  labels:
    app: {{ include "users-app.appName" . | quote }}
    release: {{ .Values.monitoring.release }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
    - nginx
  endpoints:
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.interval }}
